# Generated by Django 4.0.3 on 2022-04-10 00:06

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0012_alter_profile_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('article', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images/')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='members.profile')),
            ],
        ),
    ]
