# Generated by Django 4.0.3 on 2022-04-10 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_profile_nickname'),
        ('awwards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.IntegerField(blank=True)),
                ('usability', models.IntegerField(blank=True)),
                ('content', models.IntegerField(blank=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='awwards.projects')),
                ('score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorrates', to='members.profile')),
            ],
        ),
    ]
