# Generated by Django 4.0.3 on 2022-04-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1- Poor'), (2, '2- Bad'), (3, '3- Not Satisfying'), (4, '4- Not Good'), (5, '5- Average'), (6, '6- Fair'), (7, '7- Good'), (8, '8- Better'), (9, '9- Best'), (10, '10- Excellent')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1- Poor'), (2, '2- Bad'), (3, '3- Not Satisfying'), (4, '4- Not Good'), (5, '5- Average'), (6, '6- Fair'), (7, '7- Good'), (8, '8- Better'), (9, '9- Best'), (10, '10- Excellent')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1- Poor'), (2, '2- Bad'), (3, '3- Not Satisfying'), (4, '4- Not Good'), (5, '5- Average'), (6, '6- Fair'), (7, '7- Good'), (8, '8- Better'), (9, '9- Best'), (10, '10- Excellent')], default=0),
        ),
    ]
